### ISSUE TITLE
is there any code of decode process?

### ISSUE THREAD

**Issue by wudonglei99** [LucaCappelletti94/golomb_coding#1]

**Comment by wudonglei99** [comment]
when I get the coded content by this method, how could I decode it?

**Comment by LucaCappelletti94** [comment]
Hello @wudonglei99, I'll add the decode method for it. Do note that this is NOT meant for performant usage, but is only a didactical tool.

**Comment by wudonglei99** [comment]
ok,&nbsp; thank u very much! I will look foward the implementation of the decode method~
&nbsp;


***@***.***
***@***.***

哈工大深圳
19级博士生


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Luca ***@***.***&gt;; 
发送时间: 2022年4月5日(星期二) 晚上8:36
收件人: ***@***.***&gt;; 
抄送: ***@***.******@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LucaCappelletti94/golomb_coding] is there any code of decode process? (Issue #1)





 
Hello @wudonglei99, I'll add the decode method for it. Do note that this is NOT meant for performant usage, but is only a didactical tool.

**Comment by LucaCappelletti94** [comment]
I have published a new version with the decoding, plus I have updated the README of this repository accordingly.

**Comment by wudonglei99** [comment]
Nice, I will employ it to my experimtents, thanks for your help!



***@***.***
***@***.***

哈工大深圳
19级博士生


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LucaCappelletti94/golomb_coding"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月5日(星期二) 晚上9:52
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [LucaCappelletti94/golomb_coding] is there any code of decode process? (Issue #1)





 
I have published a new version with the decoding, plus I have updated the README of this repository accordingly.

**Comment by LucaCappelletti94** [comment]
I'm not sure what do you mean by experiments, but let me stress again that these are **didactical tools** and are only useful to quickly show the Golomb coding.

They are not useful in any other real-world context, as when actually implementing these codes in deployable applications one uses low-level languages to have access to bitstreams and generally writes the code with performance in mind.

**Comment by wudonglei99** [comment]
I got it, the experiments just several simple scientific researche cases, not the industrial deployment.
&nbsp;


***@***.***
***@***.***

哈工大深圳
19级博士生


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Luca ***@***.***&gt;; 
发送时间: 2022年4月5日(星期二) 晚上10:39
收件人: ***@***.***&gt;; 
抄送: ***@***.******@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LucaCappelletti94/golomb_coding] is there any code of decode process? (Issue #1)





 
I'm not sure what do you mean by experiments, but let me stress again that these are didactical tools and are only useful to quickly show the Golomb coding.
 
They are not useful in any other real-world context, as when actually implementing these codes in deployable applications one uses low-level languages to have access to bitstreams and generally writes the code with performance in mind.

**Comment by wudonglei99** [comment]
Hello,&nbsp; I notice&nbsp; that the example of the decoding in the github is "assert 42 == golomb_decoding(golomb_coding(42))". However,&nbsp; when I try this code in my machine, there is an error " TypeError: golomb_decoding() missing 1 required positional argument: 'b' ".&nbsp; Then I change the code to "golomb_decoding(golomb_coding(42,3),3)" , this problem is solved. I want to know how to set the required positional argument: 'b'.


***@***.***
***@***.***

哈工大深圳
19级博士生


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LucaCappelletti94/golomb_coding"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月5日(星期二) 晚上10:39
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [LucaCappelletti94/golomb_coding] is there any code of decode process? (Issue #1)





 
I'm not sure what do you mean by experiments, but let me stress again that these are didactical tools and are only useful to quickly show the Golomb coding.
 
They are not useful in any other real-world context, as when actually implementing these codes in deployable applications one uses low-level languages to have access to bitstreams and generally writes the code with performance in mind.
